/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin.web.menu.create;
import com.admin.web.menu.WebMenuFrame;
import com.database.connection.databaseConnection;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author Admin
 */
public class MenuCreateForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuCreateForm
     */
    public MenuCreateForm() {
        initComponents();
    }
    private void displayImage(File file) {
        ImageIcon imageIcon = new ImageIcon(file.getPath());
        Image image = imageIcon.getImage().getScaledInstance(menuImage.getWidth(),menuImage.getHeight(), Image.SCALE_SMOOTH);
        menuImage.setIcon(new ImageIcon(image));
    }

    
    private void openFileChooser() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            displayImage(selectedFile);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuNameTitle = new javax.swing.JLabel();
        menuName = new javax.swing.JTextField();
        descriptionTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuDetail = new javax.swing.JTextArea();
        categoryTitle = new javax.swing.JLabel();
        menuCategory = new javax.swing.JComboBox<>();
        imageOrThumbnailTitle = new javax.swing.JLabel();
        menuPrice = new javax.swing.JTextField();
        priceTitle = new javax.swing.JLabel();
        uploadImageButton = new javax.swing.JButton();
        cancelMenuButton = new javax.swing.JButton();
        createMenuButton = new javax.swing.JButton();
        menuImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 510));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuNameTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuNameTitle.setText("Menu Name");
        menuNameTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(menuNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        menuName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuName.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        descriptionTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        descriptionTitle.setText("Description");
        descriptionTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(descriptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        menuDetail.setColumns(15);
        menuDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuDetail.setRows(4);
        jScrollPane1.setViewportView(menuDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 100));

        categoryTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        categoryTitle.setText("Category");
        categoryTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(categoryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        menuCategory.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appetizers", "Main Course", "Dessert", "Beverages" }));
        menuCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(menuCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 250, -1));

        imageOrThumbnailTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imageOrThumbnailTitle.setText("Image/Thumbnail");
        imageOrThumbnailTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(imageOrThumbnailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        menuPrice.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuPrice.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(menuPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        priceTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        priceTitle.setText("Price");
        priceTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(priceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        uploadImageButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        uploadImageButton.setText("Upload");
        uploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(uploadImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, -1));

        cancelMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelMenuButton.setText("Cancel");
        cancelMenuButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        createMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        createMenuButton.setText("Create");
        createMenuButton.setPreferredSize(new java.awt.Dimension(150, 30));
        createMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));
        getContentPane().add(menuImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 140, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuButtonActionPerformed
        
        databaseConnection com = new databaseConnection();
        com.addMenu(menuName.getText(), menuDetail.getText(), 
                menuCategory.getActionCommand(), Integer.parseInt(menuPrice.getText()), menuImage.toString());
    }//GEN-LAST:event_createMenuButtonActionPerformed

    private void cancelMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenuButtonActionPerformed
        WebMenuFrame web=new WebMenuFrame();
        web.setVisible(true);
    }//GEN-LAST:event_cancelMenuButtonActionPerformed

    private void uploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageButtonActionPerformed
        // choose image from fileChooser
        openFileChooser();
    }//GEN-LAST:event_uploadImageButtonActionPerformed

    private void menuCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCreateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelMenuButton;
    private javax.swing.JLabel categoryTitle;
    private javax.swing.JButton createMenuButton;
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JLabel imageOrThumbnailTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> menuCategory;
    private javax.swing.JTextArea menuDetail;
    private javax.swing.JLabel menuImage;
    private javax.swing.JTextField menuName;
    private javax.swing.JLabel menuNameTitle;
    private javax.swing.JTextField menuPrice;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JButton uploadImageButton;
    // End of variables declaration//GEN-END:variables
}
