/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin.web.menu.update;

import com.admin.web.menu.WebMenuFrame;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author admin
 */
public class UpdateMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMenuFormm
     */
    
    public UpdateMenuForm() {
        initComponents();
    }
     private void displayImage(File file) {
        ImageIcon imageIcon = new ImageIcon(file.getPath());
        Image image = imageIcon.getImage().getScaledInstance(imageLabel.getWidth(),imageLabel.getHeight(), Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(image));
    }

    
    private void openFileChooser() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            displayImage(selectedFile);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        categoryTitle = new javax.swing.JLabel();
        foodNameTextField = new javax.swing.JTextField();
        DescriptionTitle = new javax.swing.JLabel();
        priceTitle = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JComboBox<>();
        updateMenuButton = new javax.swing.JButton();
        foodNameTitle = new javax.swing.JLabel();
        cancelMenuButton = new javax.swing.JButton();
        uploadImage2 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descriptionTextField.setColumns(15);
        descriptionTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        descriptionTextField.setRows(4);
        jScrollPane1.setViewportView(descriptionTextField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 100));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 40));

        categoryTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        categoryTitle.setText("Category");
        categoryTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(categoryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        foodNameTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        foodNameTextField.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(foodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        DescriptionTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DescriptionTitle.setText("Description");
        DescriptionTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(DescriptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        priceTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        priceTitle.setText("Price");
        priceTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(priceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        categoryTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        categoryTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appetizers", "Main Dish", "Dessert", "Beverages" }));
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(categoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 250, -1));

        updateMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updateMenuButton.setText("Update");
        updateMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        foodNameTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        foodNameTitle.setText("Food Name");
        foodNameTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(foodNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cancelMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelMenuButton.setText("Cancel");
        cancelMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 160, -1));

        uploadImage2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        uploadImage2.setText("Upload");
        uploadImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImage2ActionPerformed(evt);
            }
        });
        getContentPane().add(uploadImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 160, -1));
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 90, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
      


    }//GEN-LAST:event_categoryTextFieldActionPerformed

    private void updateMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuButtonActionPerformed
    String menuName ="";
        String description ="";
        int price = 1;
       
    }//GEN-LAST:event_updateMenuButtonActionPerformed

    private void cancelMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenuButtonActionPerformed
       WebMenuFrame webmenuframe= new WebMenuFrame();
       webmenuframe.setVisible(true);
    }//GEN-LAST:event_cancelMenuButtonActionPerformed

    private void uploadImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImage2ActionPerformed
        
        openFileChooser();
    }//GEN-LAST:event_uploadImage2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionTitle;
    private javax.swing.JButton cancelMenuButton;
    private javax.swing.JComboBox<String> categoryTextField;
    private javax.swing.JLabel categoryTitle;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JTextField foodNameTextField;
    private javax.swing.JLabel foodNameTitle;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JButton updateMenuButton;
    private javax.swing.JButton uploadImage2;
    // End of variables declaration//GEN-END:variables
}
