/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin.web.menu.update;

import com.database.connection.databaseConnection;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class UpdateMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMenuFormm
     */
//        databaseConnection.setMenuUpdate(id);
    static Map<String, String> value = databaseConnection.getMenuUpdate();
    static String id = value.get("id");

    public UpdateMenuForm() {

    }

    public UpdateMenuForm(int id) {
        initComponents();
        setLocationRelativeTo(null);
        databaseConnection.getCon();
        menuName.setText(value.get("name"));
        menuDetail.setText(value.get("detail"));
        menuPrice.setText(value.get("price"));
        menuCategory.setSelectedItem(value.get("category"));
        imgLink.setText(value.get("image"));

        System.out.println(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuDetail = new javax.swing.JTextArea();
        imgLink = new javax.swing.JTextField();
        categoryTitle = new javax.swing.JLabel();
        menuName = new javax.swing.JTextField();
        DescriptionTitle = new javax.swing.JLabel();
        priceTitle = new javax.swing.JLabel();
        menuCategory = new javax.swing.JComboBox<>();
        updateMenuButton = new javax.swing.JButton();
        foodNameTitle = new javax.swing.JLabel();
        cancelMenuButton = new javax.swing.JButton();
        uploadImage2 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        menuPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 510));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        menuDetail.setColumns(15);
        menuDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuDetail.setRows(4);
        jScrollPane1.setViewportView(menuDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 100));

        imgLink.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imgLink.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(imgLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 30));

        categoryTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        categoryTitle.setText("Category");
        categoryTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(categoryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        menuName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuName.setMinimumSize(new java.awt.Dimension(64, 30));
        menuName.setPreferredSize(new java.awt.Dimension(250, 30));
        getContentPane().add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 30));

        DescriptionTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DescriptionTitle.setText("Description");
        DescriptionTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(DescriptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        priceTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        priceTitle.setText("Price");
        priceTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(priceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        menuCategory.setEditable(true);
        menuCategory.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appetizers", "Main Dish", "Dessert", "Beverages" }));
        menuCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(menuCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 250, -1));

        updateMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updateMenuButton.setText("Update");
        updateMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 160, -1));

        foodNameTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        foodNameTitle.setText("Food Name");
        foodNameTitle.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(foodNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cancelMenuButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelMenuButton.setText("Cancel");
        cancelMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 160, -1));

        uploadImage2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        uploadImage2.setText("Upload new image");
        uploadImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImage2ActionPerformed(evt);
            }
        });
        getContentPane().add(uploadImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 250, -1));
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, 100));

        menuPrice.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        menuPrice.setPreferredSize(new java.awt.Dimension(250, 25));
        getContentPane().add(menuPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoryActionPerformed

    }//GEN-LAST:event_menuCategoryActionPerformed

    private void updateMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuButtonActionPerformed
        try {
            Integer.parseInt(menuPrice.getText());
            boolean status = databaseConnection.updateMenu(menuName.getText(), menuDetail.getText(), (String) menuCategory.getSelectedItem(), menuPrice.getText(), imgLink.getText(), id);
            if (status) {
                JOptionPane.showMessageDialog(null, "Menu Updated!!!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Menu cannot be updated..");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputted value in price is not an integer.");
        }
    }//GEN-LAST:event_updateMenuButtonActionPerformed

    private void cancelMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelMenuButtonActionPerformed

    private void uploadImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImage2ActionPerformed
        File file = databaseConnection.imageChooser();
        imgLink.setText(file.toString());
        try {
            imageLabel.setIcon(new ImageIcon(ImageIO.read(file)));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_uploadImage2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionTitle;
    private javax.swing.JButton cancelMenuButton;
    private javax.swing.JLabel categoryTitle;
    private javax.swing.JLabel foodNameTitle;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imgLink;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> menuCategory;
    private javax.swing.JTextArea menuDetail;
    private javax.swing.JTextField menuName;
    private javax.swing.JTextField menuPrice;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JButton updateMenuButton;
    private javax.swing.JButton uploadImage2;
    // End of variables declaration//GEN-END:variables
}
